import React, { useState, useEffect } from "react";
import axios from "axios";
import { dbInstance } from '../../db';
import { useNavigate } from "react-router-dom";
import {
  Row,
  Title,
  Button,
  Text,
  Container,
  ButtonContainer,
  BoxContainer,
} from "../About/About.styled";

const About = () => {
  const [isChecked, setIsChecked] = useState(false);
  const navigate = useNavigate();

  const handleCheckbox = () => {
    setIsChecked(!isChecked);
  };

  const handleContinue = async (): Promise<void> => {
    try {
      const users = await dbInstance.getData("users");
      if (!users || users.length === 0) {
        console.error("No user data found in IndexedDB");
        return;
      }

      const verifiedUser = users.find((user: any) => user.token);

      if (!verifiedUser) {
        console.error("No verified user with token found");
        return;
      }

      const userToken = verifiedUser.token;

      await axios.put(
        'https://eternalai.fly.dev/user/ternsOfPolicy', 
        { hasAcceptedPolicy: isChecked }, 
        {
          headers: {
            'Authorization': `Bearer ${userToken}`,
            'Content-Type': 'application/json',
          },
        }
      );
      
      if (isChecked) {
        navigate("/");
      }
    } catch (error) {
      console.error("Error updating policy status:", error);
    }
  };

  const handleContainerClick = () => {
    navigate("/");
  };

  const handleInnerClick = (event: React.MouseEvent) => {
    event.stopPropagation();
  };

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        handleContainerClick();
      }
    };

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, []);

  return (
    <Container onClick={handleContainerClick}>
      <BoxContainer onClick={handleInnerClick}>
        <Title>About the platform</Title>
        <Text>
          All of the characters here are not real. Everything you see and hear
          is entirely generated by Artificial Intelligence machines. The
          opinions and beliefs expressed do not represent anyone. They are
          hallucinations of a bunch of 1s and 0s inside of a magic computer.
        </Text>
        <Text>
          The creators of this platform have the best intentions with this
          project, and deeply admire each and every character on the site. You
          might even say they are our Heroes. In fact, you can say that.
        </Text>
        <Row>
          <input
            type="checkbox"
            id="text"
            checked={isChecked}
            onChange={handleCheckbox}
          />
          <label htmlFor="text">I have read the above statement</label>
        </Row>
        <ButtonContainer>
          <Button onClick={handleContinue} disabled={!isChecked}>
            CONTINUE
          </Button>
        </ButtonContainer>
      </BoxContainer>
    </Container>
  );
};

export default About;
